# ~/.config/hypr/hyprlock.conf

general {
    no_fade_in = false
    grace = 0
}

background {
    monitor = 1
#    path = /home/avvy/Imágenes/d2a6425f84f402e9310dcb7c7e46695ed4d65f45.jpg
    blur_passes = 2
}

input-field {
    monitor = 1
    size = 200, 50
    placeholder_text = <i>Contraseña...</i>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor = 1
    text = $TIME
    font_size = 64
    position = 0, 80
    halign = center
    valign = center
}
