background_opacity 0.8
dynamic_background_opacity yes
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

# Soporte de símbolos específico (opcional)
symbol_map U+E000-U+E00D,U+E010-U+E017,U+E020-U+E024,U+E030-U+E03D,U+E040-U+E042,U+E044-U+E045,U+E047-U+E048,U+E050-U+E054,U+E058,U+E05C-U+E062,U+E070-U+E073,U+E077-U+E078,U+E07A,U+E07C-U+E082,U+E085,U+E08B,U+E08E-U+E092,U+E094-U+E099,U+E09B,U+E09D-U+E09F,U+E0A0-U+E0A2,U+E0A3,U+E0B0-U+E0B3,U+E0B4-U+E0C8,U+E0CC-U+E0D2,U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E62B,U+E700-U+E7C5,U+F000-U+F2E0,U+F300-U+F31C,U+F400-U+F4A8,U+F4FB,U+F500-U+F8FF Symbols Nerd Font Mono
